### ISSUE TITLE
Key do objeto no S3 com valor ruim

### ISSUE THREAD

**Issue by igventurelli** [CovidZero/bino#2]
Ao fazer a chamada na API, o arquivo é carregado com sucesso, porém a key está estranha:

![image](https://user-images.githubusercontent.com/44559956/77125662-49a36280-6a25-11ea-8d12-7b294390a3d4.png)

**Comment by igventurelli** [comment]
Correção na PR #5 

![image](https://user-images.githubusercontent.com/44559956/77129578-52029a00-6a33-11ea-97d9-5d0283b745b0.png)

**Comment by VictorHaine** [comment]
Merged! ;)
